name = input("What is your name?: ")
print("hello:" + name)
print("I will now see if you are allowed into the net.")
birth_year = input("Enter your birth year: ")
age = 2020 - int(birth_year)
print(age) 
print("approved. welcome: " + name )